### ISSUE TITLE
Exposed github token?

### ISSUE THREAD

**Issue by andreabedini** [openmicroscopy/openmicroscopy#3646]
I noticed this [line](https://github.com/openmicroscopy/openmicroscopy/blob/develop/.travis.yml#L19). I can't see what that token used for but I don't it show be exposed at all. Travis-ci has a mechanism to protect private information, see [here](http://docs.travis-ci.com/user/encryption-keys/) for details.

**Comment by sbesson** [comment]
Hi @andreabedini, this token is used internally by our `scc travis-merge` command which bumps submodules for a given development branch and allows to merge dependent PRs (either within the same repository or across submodules). This should be a read-only token allowing to access the API without hitting the rate limit.

I certainly agree it is not an optimal solution and Travis can encrypt environment variable. However this mechanism does not apply to Pull Requests from forks for obvious security reasons and this is our main use case.

We will be moving towards a proper decoupling of our repositories and one of the consequences of this decoupling will likely be the removal of this token.

**Comment by andreabedini** [comment]
Sure, I suspected that token couldn't be used for anything nefarious.
