### ISSUE TITLE
Timezone of log files is inconsistent

### ISSUE THREAD

**Issue by ctrueden** [openmicroscopy/openmicroscopy#3838]
All the log files in `var/log` use timestamps with local time, except for `OMEROweb.log` and `OMEROweb_request.log`, which use UTC.

I very quickly looked into the code, and it seems that OMERO.web simply calls OmeroPy's configure_logging method, which uses regular Python logging, so I'm not sure why the discrepancy. But it would be good to be consistent across all the log files.

**Comment by joshmoore** [comment]
Noted in https://trello.com/c/eP7uG0X3/86-time-zone. Thanks.
