### ISSUE TITLE
Ice3.5 slice2java and omero serveur installation

### ISSUE THREAD

**Issue by remi-fr** [openmicroscopy/openmicroscopy#3958]
Hi all,

Im reopening this issue because the installation of Omero.server doesn't seem to work, while I don't have any errors reported there are no files copied to the installation folder. however, zeroc ice3.5 is correctly installed, the Omero folder is not even created by the brew omero installation formula. Is there anything I should look at ?
Here is the output I get : 
$ brew install omero --with-cpp --with-nginx
==> Installing omero from ome/homebrew-alt
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading http://downloads.openmicroscopy.org/omero/5.1.2/artifacts/openmicroscopy-5.1.2.zip
Already downloaded: /Library/Caches/Homebrew/omero-5.1.2.zip
==> ./build.py -Dice.home=/usr/local/opt/zeroc-ice35 build-all
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 83 more

Total time: 8 minutes 31 seconds

Thanks for you answer.
Remi

**Comment by sbesson** [comment]
Thanks for the report. Could you copy the full stack trace returned by the ``./build.py -Dice.home=/usr/local/opt/zeroc-ice35 build-all`` command?

**Comment by sbesson** [comment]
@remi-fr: running the same command using `VERBOSE=1`, I was able to reproduce your error and potentially identify the source of the bug. There is at least an undeclared `cmake` dependency for the `--with-cpp` option of the OMERO formula. Could you try the following:

```
brew install cmake && brew install omero --with-cpp --with-nginx
```

If that solves the installation, I will open a PR against the Homebrew formula to fix this dependency.

Best,
Sébastien

**Comment by remi-fr** [comment]
It worked I am currently installing the dependencies ! Thank you so much !

**Comment by remi-fr** [comment]
The installation of python dependencies returned that :/var/folders/jq/sxbpfjkd7njbdc45sjbww8hc0000gp/T/H5closeK9YhIc.c:1:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
    main (int argc, char **argv) {
    ^
    /var/folders/jq/sxbpfjkd7njbdc45sjbww8hc0000gp/T/H5closeK9YhIc.c:2:5: warning: implicit declaration of function 'H5close' is invalid in C99 [-Wimplicit-function-declaration]
        H5close();
        ^
    2 warnings generated.
    * Using Python 2.7.10 (default, Jul  9 2015, 13:34:07)
    * USE_PKGCONFIG: True
    .. ERROR:: Could not find a local HDF5 installation.
       You may need to explicitly state where your local HDF5 headers and
       library can be found by setting the ``HDF5_DIR`` environment
       variable or by using the ``--hdf5`` command-line option.
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/jq/sxbpfjkd7njbdc45sjbww8hc0000gp/T/pip-build-eFwJ9Y/tables

**Comment by sbesson** [comment]
Assuming you are running the `omero_python_deps` script, can you retry running your command from `/usr/local` so that the `hdf5` dependency installed by the formula can be detected - see https://github.com/ome/omero-install/blob/master/homebrew/install_omero51#L46.

**Comment by remi-fr** [comment]
Thank you again ! everything is correct now... I will sometime soon try to get Romero web up and running, so I might have some issues at that time as well, for now, have a good week !

Rémi

**Comment by sbesson** [comment]
Thanks for the update and glad to hear things are working. For all future questions about OMERO, do not hesitate to use either the [forums](https://www.openmicroscopy.org/community/) or the [mailing-lists](https://www.openmicroscopy.org/site/community/mailing-lists).
