### ISSUE TITLE
syntax error on apache default configuration

### ISSUE THREAD

**Issue by carandraug** [openmicroscopy/openmicroscopy#4513]
The default apache configuration created by omero 5.2.2, via `bin/omero web config apache`, has a syntax error:

    Syntax error on line 70 of /etc/apache2/sites-ena....
    Either all Options must start with + or -, or no Option may.

The fix is is replacing:

      Options -Indexes FollowSymLinks

with:

      Options -Indexes +FollowSymLinks

I will guess this is version dependent or someone would have found it before. This is Apache 2.4.10 running in Debian 8 (Jessie), current Debian stable.

**Comment by manics** [comment]
You can run `omero web config apache24` to generate a suitable config. I thought it was in our docs but apparently not.

**Comment by carandraug** [comment]
Thank you for the tip. Searching for apache24 on the docs I did found it on the [OMERO.server installation on Ubuntu 14.04](http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/server-linux-walkthrough.html#apache) (but I'm not in Ubuntu).

The [distro agnostic instructions for apache](http://www.openmicroscopy.org/site/support/omero5.2/sysadmins/unix/install-web/install-apache.html) don't mention it.

**Comment by joshmoore** [comment]
Thanks for pointing this out, @carandraug. See https://trello.com/c/aHKgiVXW/36-mention-apache-2-4-in-docs
