### ISSUE TITLE
Use different license of API definitions?

### ISSUE THREAD

**Issue by slnovak** [openmicroscopy/openmicroscopy#4537]
Hi,

I'd like to develop a third-party client library that uses this project's [Slice definitions](https://github.com/openmicroscopy/openmicroscopy/tree/develop/components/blitz/resources/omero/api). Unfortunately, the API definition is GPL'd according to the [license header](https://github.com/openmicroscopy/openmicroscopy/blob/develop/components/blitz/resources/omero/api/Search.ice#L4-L5). Is it possible to change the license for the API definition files so that they can be redistributed in a more friendly manner?

Thanks!

**Comment by joshmoore** [comment]
Sorry, that's not possible: all [Ice](http://zeroc.com)-based code is available strictly under the GPL or a commercial license.

**Comment by slnovak** [comment]
Thank you!
