### ISSUE TITLE
web-client: open full viewer on a new browser tab

### ISSUE THREAD

**Issue by carandraug** [openmicroscopy/openmicroscopy#4558]
When navigating the web client, I see 2 ways to open the full viewer:

* double click on the image thumbnail;
* click on the "full viewer" button in the right pane.

However, none of them allows to open the full viewer in a separate tab of the browser, it is always on a new window (with minimal browser interface). Since there is no link for the full viewer, I can't see a place where one would be able to do right click for "Open Link in New Tab".

Ideally, the following two things would be nice:

* "Full Viewer" button in the right pane is an actual link for the full viewer (but I guess there's a reason for why using `OME.openPopup('/webclient/img_detail/...` instead of a link straight to it -- I'm guessing that's to use a window with less browser clutter)
* RIght click on the web client thumbnail would bring up a context menu instead of the default browser right click menu. This context menu would include a link to that image full viewer.

---

User case: going through the thumbnails of a dataset, and select a series of them for a closer look and discussion. Currently this opens several new windows which are difficult to navigate. Multiple tabs in a single window have an order which is lost when using multiple windows.

It is possible to workaround this with a tag, but a tag suggest a more permanent classification, while the purpose of this is for the selection to expire at the end of the meeting. Our suggested workflow in the mean time is to tag all the interesting images (we are using "viewer stack"), then use the full viewer (with the "< Prev" and "Next >" buttons) on that tag.

An alternative for this would be to have the "< Prev" and "Next >" buttons on the full viewer go through the currently selected images (instead of all images in the dataset) but that sounds like substantially more work.

**Comment by will-moore** [comment]
Thanks for the suggestion.
It certainly should be possible to make both the "Full Viewer" button and the thumbnail itself into regular links, which you would then be able to right-click > Open Link in new Tab.

For a long time we have liked the idea of providing a custom right-click menu on thumbnails, but have not got around to this yet.
In the meantime it would be quite easy to add "Open in new tab" to the right-click menu for images in the tree.

Having the Prev & Next buttons only go through selected images would be quite easy to do, but I'm not sure the user workflow would be that nice. You'd have to double-click a single image to open the viewer, then go back to the webclient and select multiple images, then return to the image viewer to use Next button. This is not very intuitive.
What might be nicer is to enable a "Full Viewer" button when multiple images are selected. This could open multiple image viewers in separate windows or separate tabs.

**Comment by will-moore** [comment]
Card created https://trello.com/c/vRHQSsTs/59-full-viewer-button-to-be-link for the easiest fix.

**Comment by will-moore** [comment]
PR opened https://github.com/openmicroscopy/openmicroscopy/pull/4563

**Comment by joshmoore** [comment]
Thanks, all.
