### ISSUE TITLE
[feature request] download link for correct version of client on webclient login page

### ISSUE THREAD

**Issue by carandraug** [openmicroscopy/openmicroscopy#4657]
The webclient login page could have a link to download the insight client for the correct server version.

Assuming that omero users shouldn't have to worry about what is the underlying server version, it becomes the job of the omero admin to keep updating any internal documentation pointing to the right version of the client.

This would remove the need for such internal documentation or save the user from googling for omero client download and ending up downloading the wrong version.

**Comment by joshmoore** [comment]
@will-moore @rgozim : see an easy enough way to add this?

**Comment by manics** [comment]
The login page includes the OMERO.web version so it should be easy to add a link https://github.com/openmicroscopy/openmicroscopy/blob/v5.4.10/components/tools/OmeroWeb/omeroweb/webclient/templates/webclient/login.html#L137

**Comment by joshmoore** [comment]
Maybe `[linux] [mac] [win]` with the redirects?

```
RewriteRule ^/latest/omero5.4/insight-win.zip$ /omero/5.4.10/artifacts/OMERO.insight-5.4.10-ice36-b105-win.zip [R=seeother,L]
RewriteRule ^/latest/omero5.4/insight-mac.zip$ /omero/5.4.10/artifacts/OMERO.insight-5.4.10-ice36-b105-mac.zip [R=seeother,L]
RewriteRule ^/latest/omero5.4/insight-linux.zip$ /omero/5.4.10/artifacts/OMERO.insight-5.4.10-ice36-b105-linux.zip [R=seeother,L]
```
