### ISSUE TITLE
Exception is created but not thrown

### ISSUE THREAD

**Issue by AppChecker** [openmicroscopy/openmicroscopy#5033]
Hi!

[Static code analyzer AppChecker](https://cnpo.ru/en/solutions/appchecker.php) found some place where an exception is created, but not thrown. Perhaps it is a mistake.
1) [components/blitz/src/omero/gateway/util/PojoMapper.java, line 614](https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/blitz/src/omero/gateway/util/PojoMapper.java#L614)
```
        } catch (ClassNotFoundException e) {
            new IllegalArgumentException(pojoType + " not found");
        }
```
2) [components/blitz/src/omero/gateway/Gateway.java, line 1305](https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/blitz/src/omero/gateway/Gateway.java#L1305)
```
            } catch (Throwable e) {
                new Exception("Cannot close the connector", e);
            }
```
3) [components/blitz/src/omero/gateway/Gateway.java, line 1507](https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/blitz/src/omero/gateway/Gateway.java#L1507)
```
        } catch (Throwable e) {
            new Exception("Cannot close the derived connectors", e);
        }
```
4) [components/blitz/src/ome/formats/importer/util/HtmlMessenger.java, line 110](https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/blitz/src/ome/formats/importer/util/HtmlMessenger.java#L110)
```
        } catch (Exception e) {
            new HtmlMessengerException("Cannot create security context", e);
        }
```
5) [components/insight/SRC/org/openmicroscopy/shoola/svc/transport/BasicChannel.java, line 106](https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/insight/SRC/org/openmicroscopy/shoola/svc/transport/BasicChannel.java#L106)
```
        } catch (Exception e) {
            new TransportException("Cannot create security context", e);
        }
```

I hope this will be helpful for you

**Comment by dominikl** [comment]
Fixed by https://github.com/openmicroscopy/openmicroscopy/pull/5034 .
