### ISSUE TITLE
Some possible defects (expression/statement issues)

### ISSUE THREAD

**Issue by AppChecker** [openmicroscopy/openmicroscopy#5038]
Hi!

The next part of the weaknesses found with static analyzer [AppChecker](https://cnpo.ru/en/solutions/appchecker.php):

1) [components/insight/SRC/org/openmicroscopy/shoola/env/config/OMEROInfo.java, line 108](https://github.com/openmicroscopy/openmicroscopy/blob/f3239efa453b756e591b11964cd5b12aeb58193b/components/insight/SRC/org/openmicroscopy/shoola/env/config/OMEROInfo.java#L108)
```
	if (AgentInfo.TRUE.equals(encrypted) ||
				AgentInfo.TRUE.equals(encrypted))
```

AgentInfo.TRUE is checked twice. 
May be checked [AgentInfo.TRUE_SHORT](https://github.com/openmicroscopy/openmicroscopy/blob/f3239efa453b756e591b11964cd5b12aeb58193b/components/insight/SRC/org/openmicroscopy/shoola/env/config/AgentInfo.java#L56) ?

2) [components/insight/SRC/org/openmicroscopy/shoola/env/config/OMEROEntry.java, line 112](https://github.com/openmicroscopy/openmicroscopy/blob/f3239efa453b756e591b11964cd5b12aeb58193b/components/insight/SRC/org/openmicroscopy/shoola/env/config/OMEROEntry.java#L112)

`if (AgentInfo.TRUE.equals(value) || AgentInfo.TRUE.equals(value))`

Similarly

3) [components/server/src/ome/formats/OMEROMetadataStore.java, line 2206](https://github.com/openmicroscopy/openmicroscopy/blob/f3239efa453b756e591b11964cd5b12aeb58193b/components/server/src/ome/formats/OMEROMetadataStore.java#L2206)

		if (compare(lc.getMode(), lc2.getMode())
....
    			&& compare(lc.getNdFilter(), lc2.getNdFilter())
    			&& lc.getOtf() == lc.getOtf()
    			&& compare(lc.getPinHoleSize(), lc2.getPinHoleSize())
.....
)

Result of lc.getOtf() is compared with itself

4) [components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java, line 897](https://github.com/openmicroscopy/openmicroscopy/blob/f3239efa453b756e591b11964cd5b12aeb58193b/components/insight/SRC/org/openmicroscopy/shoola/agents/fsimporter/chooser/LocationDialog.java#L897)

```
     if (plugin == LookupNames.IMAGE_J_IMPORT ||
                plugin == LookupNames.IMAGE_J_IMPORT) 
```
Variable plugin is compared with LookupNames.IMAGE_J_IMPORT twice

5)
[components/blitz/src/ome/formats/OMEROMetadataStoreClient.java, line 1722](https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e//components/blitz/src/ome/formats/OMEROMetadataStoreClient.java#L1722)

```
            if (perm.isWorldWrite())  groupLevel = ImportEvent.GROUP_PUBLIC;
            else groupLevel = ImportEvent.GROUP_PUBLIC;
```

The both statements of the if-statement are same

**Comment by dominikl** [comment]
Fixed https://github.com/openmicroscopy/openmicroscopy/pull/5041
