### ISSUE TITLE
Some possible defects. Part 2 (strings issues)

### ISSUE THREAD

**Issue by AppChecker** [openmicroscopy/openmicroscopy#5039]
Hi!

The next part of the weaknesses found with static analyzer [AppChecker](https://cnpo.ru/en/solutions/appchecker.php):

1)
https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/blitz/src/ome/services/blitz/fire/Registry.java#L124

```
            if (client_uuid == null || client_uuid == "") {
                client_uuid = UUID.randomUUID().toString();
            }
```

It is stongly unrecommended to compare string with "", as result is not always correct: http://ideone.com/XeFo5x
It is better to use isEmpty():

```
            if (client_uuid == null || client_uuid.isEmpty()) {
                client_uuid = UUID.randomUUID().toString();
            }
```

2) https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/insight/SRC/org/openmicroscopy/shoola/env/data/model/appdata/WindowsApplicationDataExtractor.java#L250
The same as 1)

```
    if (fileDescription != "")
                applicationName = fileDescription;
```

3) https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/insight/SRC/org/openmicroscopy/shoola/env/data/model/appdata/WindowsApplicationDataExtractor.java#L252
The same as 1)

```
            else if (productName != "")
                applicationName = productName;

```
4) https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/insight/SRC/org/openmicroscopy/shoola/util/ui/UIUtilities.java#L1416
The same as 1)

`if (f == null || f == "") return null; `

5) https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e/components/server/src/ome/security/SmtpAuthenticator.java#L28
The same as 1)

`if (this.username != "" && this.password != "") {`

6) https://github.com/openmicroscopy/openmicroscopy/blob/d527261e7b4118da9dc1c924dad9bb499fc9ad8e//components/rendering/test/util/mocks/MethodSignature.java#L246

Strings ms.name and name are compared with "==", but it should be "equals"

```
   b = ms.visibility == visibility && ms.returnType == returnType
                    && ms.name == name && ms.paramTypes.length == paramTypes.length;
```

All possible defects were found by Echelon Team with [AppChecker](https://cnpo.ru/en/solutions/appchecker.php) static analyzer

**Comment by dominikl** [comment]
IMO in these cases String compare with `""` is justified, won't fix.

**Comment by mtbc** [comment]
It's not as easy for the casual reader to see that it's safe though given that we can also construct a non-interned empty string programmatically? I'd expect that `"a".substring(1) != ""`. `CollectionUtils.is(Not)Empty` includes the null-safety too.
