### ISSUE TITLE
omero.security.trustStorePassword not hidden

### ISSUE THREAD

**Issue by hajaalin** [openmicroscopy/openmicroscopy#5096]
`omero config get --hide-password` does not hide `omero.security.trustStorePassword`.

Tested on OMERO.server-5.3.0-m7.

**Comment by sbesson** [comment]
Thanks @hajaalin, this was definitely an oversight from our side. I have opened #5097 which should extend the scope of `--hide-password` and be included in OMERO 5.3.0.
