### ISSUE TITLE
OMERO.server set up feedback

### ISSUE THREAD

**Issue by hsinewu** [openmicroscopy/openmicroscopy#5508]
I was trying to make OMERO server run on Ubuntu, but kept getting stalled and got `Failed to startup some components after 300 seconds` message.

It turns out that the database tables are not created, I don't know why running `OMERO.server/bin/omero db script -f OMERO.server/db.sql --password "$OMERO_ROOT_PASS"` doesn't work for me ( I was not aware of this),but I do check the environment variable.

After log into psql and load db.sql manually, finally I'm able to start omero server. Maybe it would be good to have some meaningful **message when the database tables are not setup**?

One more thing I still don't know is `OMERO_WEB_PORT=80` given in `setting.env`, seems like it has nothing to do with during this phase? I suppose it has to do with OMERO.web, but the document in OMERO.web refer to it as `WEBPORT=80`?

Just some thoughts, thank you.

**Comment by jburel** [comment]
https://github.com/ome/omero-install/pull/167 fixes the variable name mismatch

**Comment by joshmoore** [comment]
> I was trying to make OMERO server run on Ubuntu, but kept getting stalled and got `Failed to startup some components after 300 seconds` message.

Just so that we're on the same page(s), which version are you installing and which installation instructions are you following?


> It turns out that the database tables are not created, I don't know why running `OMERO.server/bin/omero db script -f OMERO.server/db.sql --password "$OMERO_ROOT_PASS"` doesn't work for me ( I was not aware of this),but I do check the environment variable.

`omero db script` in the second-to-last line of https://docs.openmicroscopy.org/omero/5.3.4/sysadmins/unix/server-ubuntu-ice36.html#installing-omero-server generates a script for PostgreSQL. The last line (`psql ... < OMERO.server/db.sql`) executes it.

> After log into psql and load db.sql manually, finally I'm able to start omero server. Maybe it would be good to have some meaningful **message when the database tables are not setup**?

This is definitely a known issue, and sorry for the confusion. Running `bin/omero admin diagnostics` should warn you of the situation.

> One more thing I still don't know is `OMERO_WEB_PORT=80` given in `setting.env`, seems like it has nothing to do with during this phase? I suppose it has to do with OMERO.web, but the document in OMERO.web refer to it as `WEBPORT=80`?

The PR that @jburel listed should make it into the docs soon.

Thanks for all the feedback!
~Josh

**Comment by hsinewu** [comment]
Yes, I'm installing v5.3.4, following the same page you post.

Looks like I have misunderstanding about `omero db script`, it should be the psql command you mentioned that will do the real work, for some reason I didn't notice it.

That reminds me another trouble I have with psql, the **authentication method** used by postgresql was **peer** for localhost after a fresh install on my machine, which doesn't allow me to specify the username with -U option. I fail to log into database and finally figure it out, and change the authentication method to **md5**.

I think that might be the reason why my execution fails when I paste the script first time. But that seems irrelevant to omero, also I'm quite new to psql so not very sure if I read it right.

Thanks for the reply.

**Comment by joshmoore** [comment]
> That reminds me another trouble I have with psql, the authentication method used by postgresql was peer for localhost after a fresh install on my machine, which doesn't allow me to specify the username with -U option. I fail to log into database and finally figure it out, and change the authentication method to md5. ... I think that might be the reason why my execution fails when I paste the script first time. But that seems irrelevant to omero, also I'm quite new to psql so not very sure if I read it right.

As opposed to the [CentOS walk-throughs](https://docs.openmicroscopy.org/omero/5.3.4/sysadmins/unix/server-centos7-ice36.html#installing-prerequisites), the Ubuntu walk-through doesn't include configuration information. I've added https://github.com/ome/omero-install/issues/168 to track it.

Again, thanks for the feedback!
~Josh.
