### ISSUE TITLE
build.py failures on Windows

### ISSUE THREAD

**Issue by winterz** [openmicroscopy/openmicroscopy#5806]
trying to build openmicroscopy-3.4.6 on Windows 10 using MSVC2015

In  build/CMakeFiles/CMakeError.log
BUILD FAILED
C:\work\Qi\openmicroscopy-5.4.6\build.xml:157: The following error occurred while executing this line:
C:\work\Qi\openmicroscopy-5.4.6\components\antlib\resources\global.xml:439: The following error occurred while executing this line:
C:\work\Qi\openmicroscopy-5.4.6\components\antlib\resources\lifecycle.xml:190: The following error occurred while executing this line:
C:\work\Qi\openmicroscopy-5.4.6\components\antlib\resources\lifecycle.xml:170: Error running javac.exe compiler

java -version says:
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode

I no next to nothing about java.  Can you help me?

-- Running build.py to generate C++ and Ice sources; this may take some time
-- Failed to run build.py to generate C++ and Ice sources; cleaning.
CMake Error at CMakeLists.txt:110 (message):
  Failed to run build.py to generate C++ and Ice sources.  See
  CMakeFiles/OmeroBuildOutput.txt and CMakeFiles/OmeroBuildError.txt

-- Configuring incomplete, errors occurred!
See also "C:/work/Qi/openmicroscopy-5.4.6/build-msvc2015_64-x64/CMakeFiles/CMakeOutput.log".
See also "C:/work/Qi/openmicroscopy-5.4.6/build-msvc2015_64-x64/CMakeFiles/CMakeError.log".

**Comment by winterz** [comment]
I tried on OSX High Sierra and saw the same error messages.
Does work ok on a newer Fedora Linux system.  Next I'll try an older Ubuntu

**Comment by joshmoore** [comment]
Hi @winterz. Can you paste the build command that you used? Also, it would be good to see the log files mentioned. Without seeing them, my guess is going to be something like overly long command-lines.

**Comment by winterz** [comment]
Thanks for the incredibly fast response @joshmoore 
all I did was:
 cd openmicroscopy-3.6.4
 mkdir build
 cd build
 cmake ..

log files attached:
[OmeroBuildError.txt](https://github.com/openmicroscopy/openmicroscopy/files/2167946/OmeroBuildError.txt)
[OmeroBuildOutput.txt](https://github.com/openmicroscopy/openmicroscopy/files/2167947/OmeroBuildOutput.txt)

**Comment by winterz** [comment]
just tried on Ubuntu 14.04 system and got a similar error:
------------------------------------------------------------------------
BUILD FAILED
/home/build/tmp/openmicroscopy-5.4.6/build.xml:157: The following error occurred while executing thi
s line:
/home/build/tmp/openmicroscopy-5.4.6/components/antlib/resources/global.xml:439: The following error
 occurred while executing this line:
/home/build/tmp/openmicroscopy-5.4.6/components/antlib/resources/lifecycle.xml:67: impossible to res
olve dependencies:

**Comment by joshmoore** [comment]
The Windows log files are amazingly unhelpful:

```
...
generate:
Copying 8 files to C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\classes
Copying 1 file to C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\classes

compile:
Compiling 5 source files to C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\classes
[EOF]
```

```
BUILD FAILED
C:\work\Qi\openmicroscopy-5.4.6\build.xml:157: The following error occurred while executing this line:
C:\work\Qi\openmicroscopy-5.4.6\components\antlib\resources\global.xml:439: The following error occurred while executing this line:
C:\work\Qi\openmicroscopy-5.4.6\components\antlib\resources\lifecycle.xml:190: The following error occurred while executing this line:
C:\work\Qi\openmicroscopy-5.4.6\components\antlib\resources\lifecycle.xml:170: Error running javac.exe compiler

Total time: 23 seconds
```

Note sure what's going on there.

"The impossible to resolve dependencies" message is at least a lead. What's the reset of the output?

**Comment by winterz** [comment]
seems silly, but one thing in common for all the failing platforms is I don't have GTest and the build claims to be using embedded GTest.  maybe a red herring, but thought I'd mention it.

**Comment by joshmoore** [comment]
Seems unlikely at this stage of the build, but it may come back to be an issue. We may want to take a step back and attempt the pure Java build to take cmake out of the picture.

**Comment by winterz** [comment]
Here's the linux logs. look more useful to me.

[OmeroBuildOutput.txt](https://github.com/openmicroscopy/openmicroscopy/files/2168001/OmeroBuildOutput.txt)
[OmeroBuildError.txt](https://github.com/openmicroscopy/openmicroscopy/files/2168006/OmeroBuildError.txt)

**Comment by joshmoore** [comment]
```
:::: WARNINGS
		[NOT FOUND  ] commons-io#commons-io;1.4!commons-io.jar (0ms)
	==== user-maven: tried
	  /home/build/.m2/repository/commons-io/commons-io/1.4/commons-io-1.4.jar
		::::::::::::::::::::::::::::::::::::::::::::::
		::              FAILED DOWNLOADS            ::
		:: ^ see resolution messages for details  ^ ::
		::::::::::::::::::::::::::::::::::::::::::::::
		:: commons-io#commons-io;1.4!commons-io.jar
		::::::::::::::::::::::::::::::::::::::::::::::
```

is definitely a problem. https://search.maven.org/#artifactdetails%7Ccommons-io%7Ccommons-io%7C1.4%7Cjar looks reachable. Is it possible that the VM (or similar) you are using doesn't have a network connection?

**Comment by winterz** [comment]
aha.
I can wget commons-io-1.4.jar and put it under /home/build/.m2/repository/commons-io/commons-io/1.4
when I do that the build fails again, but this time with commons-logging/1.1.3

must be on the right track then.  but clearly there is a network connection since wget works.  I wonder if a network port for maven needs to be opened...  I can ask my admins about that.

**Comment by joshmoore** [comment]
I wouldn't think so. It sounds like something quite low-level with Maven/Ant jar downloading is going awry. This is the first time the `build` user is trying to perform a Java build? No local settings have been made?

**Comment by joshmoore** [comment]
I'm heading out for the evening, but you might try:

```
python build.py -d
```

and see if the (very verbose) debugging output tells us anything.

**Comment by winterz** [comment]
here's the python build.py -d  output on my Mac
[mac-build-d.txt](https://github.com/openmicroscopy/openmicroscopy/files/2168290/mac-build-d.txt)

**Comment by joshmoore** [comment]
Ah:

```
The ' characters around the executable and arguments are
not part of the command.
warning: [options] bootstrap class path not set in conjunction with -source 7
1 warning
The system is out of resources.
Consult the following stack trace for details.
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:311)
	at java.base/java.nio.file.FileTreeWalker.next(FileTreeWalker.java:373)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2752)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager$ArchiveContainer.<init>(JavacFileManager.java:523)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.getContainer(JavacFileManager.java:319)
```

How much memory do you have available?

**Comment by winterz** [comment]
Mac is solved.
Turns out I was using the Mac version of Java instead of the official Oracle version

maybe you want to document this:
for Mac make sure java -version says something like:
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

instead of:
java version "10.0.1" 2018-04-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)

Next I need to revisit what's happening on Windows.  thanks so much for your help so far.  I'm learning more about java and maven , etc,

**Comment by joshmoore** [comment]
Good luck and keep us posted!

**Comment by winterz** [comment]
Here's the output of 'python build.py -d' .  seems that it doesn't like slice2java.
[windows-build-d.txt](https://github.com/openmicroscopy/openmicroscopy/files/2171144/windows-build-d.txt)

the strange this is, if I run %ICE_HOME%\bin\slice2java --version works and prints 3.4.6
I don't know why build.py isn't happy

**Comment by joshmoore** [comment]
I would expect a better error message but only Ice 3.5 and 3.6 are supported:

http://docs.openmicroscopy.org/omero/5.4.6/sysadmins/version-requirements.html?highlight=version%20requirements#ice

**Comment by winterz** [comment]
sorry, typo. 
slice2java --version does print 3.6.4  (not 3.4.6 as I stated above)

but solved anyway, I forgot to put %ICE_HOME%\bin into %PATH%

**Comment by winterz** [comment]
@joshmoore sorry to be a pain.
On Windows if I use the CMake build, I'm seeing:
scons: *** [omero_api_Exporter_ice.py] The system cannot find the file specified

I hand-edited the top-level CMakeLists.txt to run 'python build.py -d' instead of 'python build.py build-default' so I could see what's breaking.

Funny thing is, I'm pretty darn sure running python build.py -d on the command line works ok.

**Comment by joshmoore** [comment]
Hi @winterz, sorry but this got lost in the vacation deluge. Did you have an success in the interim? If not, do you want to attach the related log files and I'll take a look?

**Comment by winterz** [comment]
Yeah, I just returned from vacation as well.
The last time I tried I was still getting stuck in the same place with that scons failure.

I will send you all the log files I can find. might take me a few days to get things in order first.

**Comment by winterz** [comment]
[OmeroBuildError.txt](https://github.com/openmicroscopy/openmicroscopy/files/2333505/OmeroBuildError.txt)
[OmeroBuildOutput.txt](https://github.com/openmicroscopy/openmicroscopy/files/2333506/OmeroBuildOutput.txt)

attaching the logs from running:
cmake -G "NMake Makefiles" -Dtest=OFF -DCMAKE_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=c:\omero ..
nmake 

I'm building against the ICE I installed from  http://zeroc.com/download/Ice/3.6/Ice-3.6.4-WebInstaller.exe
ICE_HOME=c:\Program Files (x86)\ZeroC\Ice-3.6.4

**Comment by winterz** [comment]
exact same error if I build ICE myself and build OMERO against that.

**Comment by winterz** [comment]
[foo.txt](https://github.com/openmicroscopy/openmicroscopy/files/2336597/foo.txt)

foo.txt is the output of running build.py -d by itself without cmake being involved.

**Comment by winterz** [comment]
I wonder if scons is being run "naked". i.e. without running python scons.py

**Comment by joshmoore** [comment]
Taking a look...

**Comment by joshmoore** [comment]
Reading through the debug output:

```
scons: *** [omero_api_Exporter_ice.py] The system cannot find the file specified
```

For me that file is under:
```
$ find . -name omero_api_Exporter_ice.py
./components/blitz/generated/omero_api_Exporter_ice.py
```

Along with a number of other ones:

```
$ ls ./components/blitz/generated/*_ice.py | wc
     232     232   14032
```

And for you?

Also:

```
	retrieving C:\work\Qi\openmicroscopy-5.4.6\lib\cache\commons-beanutils\commons-beanutils\jars\commons-beanutils-1.8.0.jar
		to C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\libs\commons-beanutils.jar

 executing "ln -s -f C:\work\Qi\openmicroscopy-5.4.6\lib\cache\commons-beanutils\commons-beanutils\jars\commons-beanutils-1.8.0.jar C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\libs\commons-beanutils.jar"
symlink failed; falling back to copy (java.io.IOException: Cannot run program "ln": CreateProcess error=2, The system cannot find the file specified)
java.io.IOException: Cannot run program "ln": CreateProcess error=2, The system cannot find the file specified
```

What do you see at ` C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\libs\commons-beanutils.jar`?

**Comment by winterz** [comment]
I don't have components\blitz\generated\omero_api_Exporter_ice.py
I don't have any *_ice.py files under components\blitz\generated

I do have a C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\libs\commons-beanutils.jar
(not a symlink, but the copy seems correct)

**Comment by winterz** [comment]
I don't have components\blitz\generated\omero_api_Exporter_ice.py
I don't have any *_ice.py files under components\blitz\generated

I do have a C:\work\Qi\openmicroscopy-5.4.6\components\dsl\target\libs\commons-beanutils.jar
(not a symlink, but the copy seems correct)

**Comment by winterz** [comment]
aha.  got farther.
slice2py is not built by default on Windows.
I ran 'c:\python27\Scripts\pip install zeroc-ice==3.6.4'  and make sure you have c:\python27\scripts in %PATH%

I'd like to figure out how to build slice2py instead of relying on pip, just like is done on linux and osx

Now the build.py step completes ok.

Next big problem:  linking omero-ice library has thousands of unresolved symbols.

**Comment by winterz** [comment]
I'm as far on the Windows build as I can get.
I can either use the pip install for slice2py as described in the previous comment or I can build+install by running make && make install inside cpp\src\slice2py.

the big blocker is when trying to link omero-ice.dll we hit the link.exe error:
"LINK : fatal error LNK1189: library limit of 65535 objects exceeded"

there is no way to increase the number of objects in a Windows dll, the only solution is to reduce the number of objects or split the library

**Comment by joshmoore** [comment]
@winterz: if you're hitting the object limit, the options that come to mind are:

 * attempt to build slice2py for Ice 3.5 though it may have similar issues with the limit
 * attempt to strip out slice definitions that you won't be using
 * make a push for Ice 3.7 which will likely require server changes as well
 * define your own service, but that will need implementing in a non-C++ language server side

Sorry that I don't have better news for you.

**Comment by winterz** [comment]
thanks Josh for your continuing support.
I will ask about using ice3.7.  certainly doesn't hurt to do some test builds and see it the object limit problem goes away.   then I should move to omero 5.4.7, right?

**Comment by joshmoore** [comment]
> I will ask about using ice3.7. certainly doesn't hurt to do some test builds and see it the object limit problem goes away.

If you can tell us that, then it will certainly bump the value of migrating.

> then I should move to omero 5.4.7, right?

My current understanding is that an ice37 client will *not* be able to talk to an OMERO 5.4.7 (or upcoming 5.4.8) server, at least not without some work.

**Comment by winterz** [comment]
ice3.7 doesn't install a 'slice' top-level so omero-5.4.6 nor 5.4.7 will build . it fails to find ICE in the FindIce.cmake

i.e.
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Failed to find all Ice components (missing: Ice_SLICE_DIR
  _Ice_REQUIRED_LIBS_FOUND) (found suitable version "3.7.1", minimum required
  is "3.5.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  components/tools/OmeroCpp/cmake/FindIce.cmake:423 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:71 (find_package)

**Comment by winterz** [comment]
ah, make install-slice
I see the buildsystem is different now. I better read the instructions.

**Comment by winterz** [comment]
omero has lots of problems with ice 3.7.1 .  Next attempt is to see if I can downgrade to ice 3.5.1 on windows. 

BTW: https://docs.openmicroscopy.org/omero/5.4.6/developers/Cpp.html documents the "65535 objects exceeded" problem so this is already well-known.

I'm going to close this thread as I've taken things as far as I can for the various platforms.
