### ISSUE TITLE
Which OS is the openjdk:8 image built upon?

### ISSUE THREAD

**Issue by iNLyze** [openmicroscopy/openmicroscopy#5863]
Please excuse the newb nature of the question: 
The Dockerfiles builds using the image `openjdk:8` from Dockerhub. Which OS ist this built upon?
The OMERO docs have guides for, e.g. CentOS 7 and Ubuntu 16.04, so it isn't quite clear to me. You are using `yum`, so most likely it is not Ubuntu.

**Comment by joshmoore** [comment]
> Please excuse the newb nature of the question:

No worries, @iNLyze 

> Which OS ist this built upon?

https://github.com/docker-library/openjdk/blob/86918ee28d383e7af63f535a2558040dce141099/8/jdk/Dockerfile is based on Debian stretch. cF:

```
   Ubuntu      |       Debian  
18.04  bionic     buster  / sid   - 10
17.10  artful     stretch / sid   - 9
17.04  zesty      stretch / sid
16.10  yakkety    stretch / sid
16.04  xenial     stretch / sid
15.10  wily       jessie  / sid   - 8
15.04  vivid      jessie  / sid
14.10  utopic     jessie  / sid
14.04  trusty     jessie  / sid
13.10  saucy      wheezy  / sid   - 7
13.04  raring     wheezy  / sid
12.10  quantal    wheezy  / sid
12.04  precise    wheezy  / sid
11.10  oneiric    wheezy  / sid
11.04  natty      squeeze / sid   - 6
10.10  maverick   squeeze / sid
10.04  lucid      squeeze / sid
```

from https://askubuntu.com/questions/445487/what-debian-version-are-the-different-ubuntu-versions-based-on

Hope that helps.
