### ISSUE TITLE
Referencing images in OMERO

### ISSUE THREAD

**Issue by nyue** [openmicroscopy/openmicroscopy#5939]
Hi,

  I am new to OMERO and so my terminology may not be super accurate.

  What feature in OMERO should I look into if I want to reference images stored in OMERO via a URL. We plan to generate scientific reports (some of them in HTML format) which references work done by other scientists who will be using OMERO (when we get it installed and setup), we want the reader of the report to either see the image directly (possibly via the img tag) or via some other URL means (maybe launch some simple viewer)

Cheers

**Comment by joshmoore** [comment]
Hi @nyue. The first step will be setting up a public user. Documentation is under https://docs.openmicroscopy.org/omero/5.4.9/sysadmins/public.html

Towards the bottom of that page you'll see examples of URLs that you can then share:

* https://omero.lifesci.dundee.ac.uk/webclient/?show=project-27936

takes you to the overview page. Clicking on an image, you can use the link symbol:

![screen shot 2019-01-10 at 09 18 51](https://user-images.githubusercontent.com/88113/50955203-c5685d80-14b8-11e9-922b-a8c09887a506.png)

to get an image-specific URL:

 * https://omero.lifesci.dundee.ac.uk/webclient/?show=image-4154018

When you double-click on the image, you'll get a new URL:

 * https://omero.lifesci.dundee.ac.uk/webclient/img_detail/4154018/?dataset=73132

which will resolve, e.g., on twitter. Right clicking on that image, you'll get a single jpeg URL:

 * https://omero.lifesci.dundee.ac.uk/webclient/render_image/4154018/35/0/?c=1|0:2996$0000FF,2|47:5844$00FF00,3|0:10468$FF0000,-4|29:3793$FF0000&m=c&p=normal&ia=0&q=0.9&maps=[{%22inverted%22:{%22enabled%22:false}},{%22inverted%22:{%22enabled%22:false}},{%22inverted%22:{%22enabled%22:false}},{%22inverted%22:{%22enabled%22:false}}]

which can be used in an `<img src=` element.

Hope that helps.
~Josh

**Comment by joshmoore** [comment]
Closing, but feel free to comment.
