### ISSUE TITLE
log lines in master.err on server startup

### ISSUE THREAD

**Issue by mtbc** [openmicroscopy/openmicroscopy#6049]
When OMERO.server starts up many innocuous log lines are written into `master.err`.

**Comment by mtbc** [comment]
https://merge-ci.openmicroscopy.org/jenkins/job/OMERO-server/ws/OMERO.server/var/log/master.err/*view*/ has an example.

**Comment by joshmoore** [comment]
That looks like someone turned on a good deal of logging for debugging purposes.

**Comment by mtbc** [comment]
My first mention of it on Slack seems to be May 16 so I guess it happened before then.

**Comment by joshmoore** [comment]
Looks like this is an issue with jcl-over-slf4j having been removed from our dependency graph. Looking at a solution.
