### ISSUE TITLE
CentOS-7 postgresql10 variant installation source?

### ISSUE THREAD

**Issue by truatpasteurdotfr** [openmicroscopy/openmicroscopy#6090]
https://docs.openmicroscopy.org/omero/5.5.1/sysadmins/unix/server-centos7-ice36.html is mentionning installing a postresql version 10 from postgresql.org. Would it also be possible to complete the installation with the scl/rh version https://www.softwarecollections.org/en/scls/rhscl/rh-postgresql10 or are there any known issues?

**Comment by joshmoore** [comment]
There aren't any known issues with the scl/rh packages or other builds of PostgreSQL other than version 10.9: see https://forum.image.sc/t/fyi-not-possible-to-create-new-omero-instance-with-latest-postgresql-versions/26929 for more info.

If you give find a new package to work well for you, please let us know.

All the best,
~Josh

**Comment by truatpasteurdotfr** [comment]
thanks, I will try with rh-postgresql10-postgresql-server-10.6-1.el7.x86_64
