### ISSUE TITLE
Alternate gradle/maven artifactory location?

### ISSUE THREAD

**Issue by bbimber** [openmicroscopy/openmicroscopy#6259]
Hello,

We use the omero java client, which is part of our gradle build. As you might know, openmicroscopy.org went down this weekend, and another similar disruption happened within the last year or two. Are the artifacts deployed to any other locations, and/or would you consider deploying releases to a different repository as a backup?

Thanks,
Ben Bimber

**Comment by joshmoore** [comment]
Hi @bbimber. Yes, it's definitely been one of those years....  You can find out more information under https://forum.image.sc/t/ome-resources-down-due-to-uod-outage/43956 but rest assured that are feverishly working on a solution. There's currently no full clone of artifacts.o.org though you may be able to find some of the artifacts that you need on https://maven.scijava.org/.  We're focusing on getting a server running in a new location and we'll get back to you as quickly as we can.

All the best,
~Josh

**Comment by bbimber** [comment]
in case anyone else reads this, Glencoe software replied with these mirrors too:


•	https://maven.scijava.org/content/groups/public
•	https://artifacts.glencoesoftware.com/artifactory/repo

**Comment by sbesson** [comment]
Closing for now as https://artifacts.openmicroscopy.org/ is now redirecting to @glencoesoftware artifactory and should be largely functionaly. Feel free to point at ongoing issues with fetching artifacts.
As mentioned above, SciJava's Nexus is an another location which should have an up-to-date mirror of OME artifacts.
