### ISSUE TITLE
CZI file Exposure time 

### ISSUE THREAD

**Issue by CFGrote** [openmicroscopy/openmicroscopy#6266]
### Summary
We experience problems with how exposure time is reported in in the Acquisition tab under Image. Reported values are off by factor 1000.

### Details:
The exposure times for 3 channels are set to 25, 500, and 1000 ms, respectively and these values are correctly recorded in the czi file as reported by  Zen:  
![zen](https://user-images.githubusercontent.com/15476807/109470097-3db28400-7a6f-11eb-90d9-a63710ae64b3.png)  

In omero, under Aqquisition/Image  I get these values:  
Bright: 25s (=25000 ms)
RFP: 16min40s (=1000000 ms)
EGFP: 8min20s (=500000 ms)

![Screenshot_2021-03-01_09-31-03](https://user-images.githubusercontent.com/15476807/109471299-e0b7cd80-7a70-11eb-8c63-c8b0e80b17e2.png)  

**NOTE**: The wavelengths are wrong, too, but that's a problem on our side.

"Original metadata" has two entries per channel that match "ExposureTime":
"Experiment|AcquisitionBlock|MultiTrackSetup|Track|Channel|DataGrabberSetup|CameraFrameSetup|ExposureTime":  
![Screenshot_2021-03-01_09-27-53](https://user-images.githubusercontent.com/15476807/109471721-74899980-7a71-11eb-9e1a-c0878f196e1f.png)  
These values are correct.

The 2nd entry is  
"Information|Image|Channel|ExposureTime":  
![Screenshot_2021-03-01_09-28-11](https://user-images.githubusercontent.com/15476807/109471739-781d2080-7a71-11eb-95d8-a549b38920cf.png)

These values are off by 3 powers of 10 and it looks to me that this is what omero bases it's report in the Acquisition tab on.

We're in touch with people at Zeiss to clarify the meaning of the different exposure time entries in the czi metadata.

Thanks for any suggestions.

Omero Version 5.6.2

**Comment by CFGrote** [comment]
Possibly related: https://github.com/ome/bioformats/issues/3648

**Comment by CFGrote** [comment]
Example czi to reproduce this issue:
https://demo.openmicroscopy.org/webclient/?show=image-165834

**Comment by dgault** [comment]
Hi @CFGrote , thank you for raising the issue and providing sample data. I believe this problem is the same as the existing Bio-Formats issue you mentioned above (the original issue was https://github.com/ome/bioformats/issues/3560). I will copy your comment and findings onto that original issue to keep all the feedback in one place.

**Comment by CFGrote** [comment]
thanks!
