### ISSUE TITLE
Fix JSON API JavaScript login example

### ISSUE THREAD

**Issue by will-moore** [openmicroscopy/openmicroscopy#6274]
https://github.com/ome/openmicroscopy/blob/develop/examples/Training/javascript/index.html 
example is not working. Get a 403 (CSRF) error. 

See discussion at https://forum.image.sc/t/do-you-have-an-example-of/51887/2

- [x] http support
- [ ] https support

**Comment by jburel** [comment]
Changes in https://github.com/ome/openmicroscopy/pull/6276 improve the example.
It is still not working with https.
